@echo off
chcp 65001 >nul 2>&1
title GGUF → Ollama 一键注册工具
echo ═══════════════════════════════════════════
echo   GGUF → Ollama 一键注册工具 v1.0
echo   扫描 D:\models\ 下所有 .gguf 文件
echo   自动注册到 Ollama
echo ═══════════════════════════════════════════
echo.

:: ── 配置 ──
set "MODELS_DIR=D:\models"
set "OLLAMA_EXE=C:\Users\Matebook\AppData\Local\Programs\Ollama\ollama.exe"
set "WORK_DIR=%TEMP%\ollama_register"

:: ── 检查 Ollama ──
if not exist "%OLLAMA_EXE%" (
    echo [错误] 未找到 Ollama: %OLLAMA_EXE%
    echo 请修改脚本中的 OLLAMA_EXE 路径
    pause
    exit /b 1
)

echo [信息] Ollama 路径: %OLLAMA_EXE%
for /f "tokens=2 delims= " %%v in ('"%OLLAMA_EXE%" --version 2^>^&1') do (
    echo [信息] Ollama 版本: %%v
)
echo.

:: ── 创建工作目录 ──
if exist "%WORK_DIR%" rmdir /s /q "%WORK_DIR%"
mkdir "%WORK_DIR%"

:: ── 扫描 GGUF 文件 ──
echo [扫描] 正在搜索 %MODELS_DIR% 下的 .gguf 文件...
echo.

set /a COUNT=0
for /r "%MODELS_DIR%" %%f in (*.gguf) do (
    set /a COUNT+=1
    set "GGUF_PATH=%%f"
    set "GGUF_NAME=%%~nf"

    :: ── 从路径中提取系列名 (倒数第二级目录) ──
    for %%d in ("%%~dpf..") do set "SERIES=%%~nxd"

    :: ── 清理模型名 (去掉量化后缀) ──
    set "MODEL_NAME=!GGUF_NAME!"

    :: 构建模型名: 小写，用连字符，去掉 .Q 后缀
    set "MODEL_NAME=!GGUF_NAME:.Q4_K_M=!"
    set "MODEL_NAME=!GGUF_NAME:.Q5_K_M=!"
    set "MODEL_NAME=!GGUF_NAME:.Q6_K=!"
    set "MODEL_NAME=!GGUF_NAME:.Q8_0=!"
    set "MODEL_NAME=!GGUF_NAME:.Q3_K_M=!"
    set "MODEL_NAME=!GGUF_NAME:.Q2_K=!"
    set "MODEL_NAME=!GGUF_NAME:.F16=!"
    set "MODEL_NAME=!GGUF_NAME:.F32=!"
    set "MODEL_NAME=!GGUF_NAME: =-!"

    echo ─────────────────────────────────────
    echo [!COUNT!] 文件: %%~nxf
    echo     路径: %%f
    echo     大小: %%~zf bytes
    echo     注册名: !MODEL_NAME!
    echo.

    :: ── 生成 Modelfile ──
    set "MODELFILE=%WORK_DIR%\Modelfile_!MODEL_NAME!"
    (
        echo # Auto-generated by GGUF-2-Ollama
        echo # Source: %%f
        echo FROM "%%f"
        echo.
        echo PARAMETER temperature 0.7
        echo PARAMETER top_p 0.9
        echo PARAMETER num_ctx 4096
        echo.
        echo SYSTEM """You are a helpful AI assistant. Respond concisely and accurately in the same language as the user's question."""
    ) > "!MODELFILE!"

    echo     [创建] Modelfile 已生成

    :: ── 注册到 Ollama ──
    echo     [注册] 正在执行 ollama create !MODEL_NAME! ...
    "%OLLAMA_EXE%" create "!MODEL_NAME!" -f "!MODELFILE!"
    if !errorlevel! equ 0 (
        echo     [成功] !MODEL_NAME! 已注册到 Ollama
    ) else (
        echo     [失败] !MODEL_NAME! 注册失败，请检查错误信息
    )
    echo.
)

:: ── 汇总 ──
echo ═══════════════════════════════════════════
echo   注册完成! 共处理 %COUNT% 个 GGUF 模型
echo ═══════════════════════════════════════════
echo.
echo [验证] 当前 Ollama 已注册模型列表:
echo.
"%OLLAMA_EXE%" list
echo.

:: ── 清理 ──
rmdir /s /q "%WORK_DIR%" 2>nul

pause
