#!/usr/bin/env python3
"""
GGUF → Ollama 一键注册工具 v1.0
自动扫描 D:\models\ 下所有 .gguf 文件，注册到 Ollama
"""

import os
import re
import subprocess
import sys
from pathlib import Path

# ═══════════════════ 配置区 ═══════════════════
MODELS_DIR = Path(r"D:\models")
OLLAMA_EXE = Path(r"C:\Users\Matebook\AppData\Local\Programs\Ollama\ollama.exe")
# 系统提示词 (可根据需要修改)
SYSTEM_PROMPT = "You are a helpful AI assistant. Respond concisely and accurately in the same language as the user's question."
# ══════════════════════════════════════════════


def find_ollama() -> Path:
    """查找 Ollama 可执行文件"""
    candidates = [
        OLLAMA_EXE,
        Path.home() / "AppData" / "Local" / "Programs" / "Ollama" / "ollama.exe",
    ]
    # 尝试 PATH
    for p in candidates:
        if p.exists():
            return p
    # 搜索 PATH
    for p in os.environ.get("PATH", "").split(os.pathsep):
        candidate = Path(p) / "ollama.exe"
        if candidate.exists():
            return candidate
    return None


def scan_gguf(base_dir: Path) -> list[dict]:
    """递归扫描目录下所有 .gguf 文件"""
    results = []
    for gguf_file in sorted(base_dir.rglob("*.gguf")):
        size_mb = gguf_file.stat().st_size / (1024 * 1024)
        results.append({
            "path": gguf_file,
            "name": gguf_file.stem,          # 如 "Hermes-3-Llama-3.2-3B.Q4_K_M"
            "size_mb": round(size_mb, 1),
            "parent_dir": gguf_file.parent.name,
        })
    return results


def clean_model_name(raw_name: str) -> str:
    """
    从 GGUF 文件名生成干净的 Ollama 模型名
    去掉量化后缀，转小写，空格变连字符
    """
    name = raw_name.lower()
    # 去掉常见量化后缀
    quant_suffixes = [
        r"\.q2_k", r"\.q3_k_m", r"\.q3_k_s", r"\.q3_k_l",
        r"\.q4_0", r"\.q4_1", r"\.q4_k_m", r"\.q4_k_s",
        r"\.q5_0", r"\.q5_1", r"\.q5_k_m", r"\.q5_k_s",
        r"\.q6_k", r"\.q8_0",
        r"\.f16", r"\.f32", r"\.bf16",
        r"\.iq4_nl", r"\.iq4_xs",
    ]
    for suffix in quant_suffixes:
        name = re.sub(suffix + r"$", "", name, flags=re.IGNORECASE)
    # 空格变连字符
    name = name.replace(" ", "-")
    return name


def extract_quant(raw_name: str) -> str:
    """提取量化等级用于显示"""
    match = re.search(r"\.(q[0-9]_[kms]_?[kmsl]?|f1[632]|bf16|iq[0-9]_[a-z]+)", raw_name, re.IGNORECASE)
    return match.group(1).upper() if match else "?"


def create_modelfile(gguf_path: Path, model_name: str) -> str:
    """生成 Ollama Modelfile 内容"""
    return f"""# Auto-generated by gguf-to-ollama.py
# Source: {gguf_path}
# Model: {model_name}
FROM "{gguf_path}"

PARAMETER temperature 0.7
PARAMETER top_p 0.9
PARAMETER num_ctx 4096

SYSTEM """{SYSTEM_PROMPT}"""
"""


def register_model(ollama: Path, model_name: str, modelfile_content: str, work_dir: Path) -> bool:
    """通过 ollama create 注册模型"""
    modelfile_path = work_dir / f"Modelfile.{model_name}"
    modelfile_path.write_text(modelfile_content, encoding="utf-8")

    try:
        result = subprocess.run(
            [str(ollama), "create", model_name, "-f", str(modelfile_path)],
            capture_output=True, text=True, timeout=300,
        )
        if result.returncode == 0:
            return True
        else:
            print(f"    [错误] {result.stderr.strip()}")
            return False
    except subprocess.TimeoutExpired:
        print(f"    [错误] 注册超时（300秒）")
        return False
    except Exception as e:
        print(f"    [错误] {e}")
        return False


def main():
    print("═" * 50)
    print("  GGUF → Ollama 一键注册工具 v1.0")
    print("═" * 50)
    print()

    # 查找 Ollama
    ollama = find_ollama()
    if not ollama:
        print("[错误] 未找到 Ollama，请确保已安装")
        sys.exit(1)
    print(f"[信息] Ollama: {ollama}")

    try:
        result = subprocess.run([str(ollama), "--version"], capture_output=True, text=True)
        print(f"[信息] 版本: {result.stdout.strip()}")
    except Exception as e:
        print(f"[警告] 无法获取版本: {e}")
    print()

    # 扫描 GGUF
    if not MODELS_DIR.exists():
        print(f"[错误] 模型目录不存在: {MODELS_DIR}")
        sys.exit(1)

    gguf_files = scan_gguf(MODELS_DIR)
    if not gguf_files:
        print(f"[信息] 在 {MODELS_DIR} 下未找到任何 .gguf 文件")
        print("请先将 LM Studio 下载的模型放到此目录")
        sys.exit(0)

    print(f"[扫描] 在 {MODELS_DIR} 下找到 {len(gguf_files)} 个 GGUF 文件:")
    print()
    for i, f in enumerate(gguf_files, 1):
        quant = extract_quant(f["name"])
        model_name = clean_model_name(f["name"])
        print(f"  {i}. {f['name']}")
        print(f"     路径: {f['path']}")
        print(f"     大小: {f['size_mb']} MB | 量化: {quant}")
        print(f"     → 注册名: {model_name}")
        print()

    # 确认
    confirm = input("是否全部注册? [Y/n]: ").strip().lower()
    if confirm in ("n", "no"):
        print("已取消")
        sys.exit(0)

    # 逐个注册
    print()
    print("═" * 50)
    print("  开始注册")
    print("═" * 50)
    print()

    import tempfile
    work_dir = Path(tempfile.mkdtemp(prefix="ollama_reg_"))
    success_count = 0
    fail_count = 0

    for i, f in enumerate(gguf_files, 1):
        model_name = clean_model_name(f["name"])
        quant = extract_quant(f["name"])
        print(f"[{i}/{len(gguf_files)}] 注册 {model_name} ({quant}) ...")

        modelfile_content = create_modelfile(f["path"], model_name)
        if register_model(ollama, model_name, modelfile_content, work_dir):
            success_count += 1
            print(f"    [成功] {model_name}")
        else:
            fail_count += 1
            print(f"    [失败] {model_name}")
        print()

    # 清理
    import shutil
    shutil.rmtree(work_dir, ignore_errors=True)

    # 汇总
    print("═" * 50)
    print(f"  完成! 成功: {success_count}  失败: {fail_count}")
    print("═" * 50)
    print()

    # 列出已注册模型
    print("[验证] Ollama 模型列表:")
    print()
    try:
        result = subprocess.run([str(ollama), "list"], capture_output=True, text=True)
        print(result.stdout)
    except Exception as e:
        print(f"[警告] 无法列出模型: {e}")

    if success_count > 0:
        print()
        print("[提示] 使用方法:")
        print(f'  {ollama.parent}\\ollama.exe run {clean_model_name(gguf_files[0]["name"])}')
        print(f'  或在代码中: client = OpenAI(base_url="http://localhost:11434/v1")')


if __name__ == "__main__":
    main()
